name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    # prevents this action from running on forks
    if: github.repository == 'FaberVitale/solid-bricks'
    name: Release
    env:
      CI: "true"
      HUSKY: "0"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm run build:packages

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

